### ISSUE TITLE
how make open world

### ISSUE THREAD

**Issue by cvargas22** [gheshu/gputracer#1]
Hi, i'm using your path tracer and made some changes like move the light by keyboard, and other things, im trying to create a open world, to see how the algorithm (path tracer) change and improves the scene, i remove the walls and ceiling from the depth shader but all the scene turns black and only see the spheres, light and floor. Can you help me please? thx

PD: sorry for my bad english, im from Chile (south america)

**Comment by Vethanis** [comment]
Thanks for checking out my path tracer. Unfortunately path tracers don't do so great on open space, they have to have something to bounce off of in order trace light back to the eye. 

A larger scene might use a ground plane for the earth and a large hemisphere as the 'sky'. Having every ray hit something greatly increases the chance the eye will reach a light and be able to see. This is why the example scene is a fully enclosed box.

**Comment by cvargas22** [comment]
Thanks for the tip. I'm doing a research for path tracing, and i want to do some test scenarios for your path tracer (closed box, open scene, etc). Your path tracer works very well.

I have another doubt, how i can put meshes for create 3d images (for a open world) like mountains, caves , etc. In this example you create the scene in the depth.glsl with a Map Function, but i dont know how to load the meshes from your code. Hope you can resolve my doubt, thanks!

**Comment by Vethanis** [comment]
This path tracer is designed to only use signed distance functions for defining the scene. If you wish to use triangles to define your scene then you will want to use some sort of [bounding volume hierarchy](https://en.wikipedia.org/wiki/Bounding_volume_hierarchy). An example would be to use an octree to subdivide the triangles in your scene. This allows you to compute ray-triangle intersections at a log base 8 complexity rather than one linear with the number of triangles in your scene. 

I recommend checking out this blog for more info: https://www.scratchapixel.com/index.php?redirect

**Comment by Vethanis** [comment]
There are ways to make open worlds with signed distance functions, however. There are several good examples on shadertoy, like this one: https://www.shadertoy.com/view/MdX3Rr

**Comment by cvargas22** [comment]
Thanks for the link and hello again, i have follow the procedural way. But i have another doubt of your path tracer, you define a map.txt file, for properties material, but i dont know which means each value of the file, for example in the first line we have properties of the light, the 3 first element are RGB , and the others values of the line, and the values for the other lines (1 to 16)?, that's my doubt, hope you can help me to know what means each value in the txt file

**Comment by Vethanis** [comment]
The material system could be improved. The current format is a vec4 for reflectance, then a vec4 for emittance, on each line. 

The reflectance determines what colors are absorbed / reflected when reflecting across the material. For example, if you emit white light at a red surface, all non-red color will be absorbed and turned into heat while red will be reflected and be the visible color of the object. 

Emittance determines what spectrum of light an object emits, and what intensity. I keep all these values between 0 and 1 to attempt some conservation of energy. 

The w channel in emittance is used as a roughness parameter that determines how coherent a ray is when reflecting off of that material's surface. Higher values will cause the reflected ray to bounce in more random directions while lower values will be more like a pure reflection across a perfect mirror.

https://github.com/gheshu/gputracer/blob/master/src/depth.glsl#L22
https://github.com/gheshu/gputracer/blob/master/src/depth.glsl#L202
https://github.com/gheshu/gputracer/blob/master/src/depth.glsl#L242
