### ISSUE TITLE
Some questions to modify source code for large open worlds

### ISSUE THREAD

**Issue by crinavar** [gheshu/gputracer#2]
Dear Lauren,

Your repository has become a great base for learning path tracing and some aspects that are not trivial when implementing it from scratch, we really appreciate your work. Right know we are trying to extend your implementation to open enviroments (like landscapes). I have some issues for which I would really appreciate if you could help with a few advices or directions:
Our current work is held here
https://github.com/cvargas22/Path-Tracer-OpenGL
you can run it as 
./prog width height mode
mode: 1 for closed, 2 for open enviroment
(if you would like to extend the citation of your work in the github description please let us know)

1) When we modify the number of bounces i see an inmediate effect which is what one can expect and its ok. But when I increase the number of steps (from 45 to 1000), I expect to see an increase in quality for each frame, but I dont see any improvement at all. I think I am not understanding where the "quality" part is in the code, related to the amount of sampling. What can be an efficient way for increasing the quality per frame??.Right know as i write this i just realized that i could just run internally a few frames before updating the framebuffer, which would increase the quality per visible frame. Do you know if I can achieve this in a more elegant way inside the shader??

2) For large open scenarios, I am trying to achieve proper lighting and shadows as they look in open fields (shadow areas not too illuminated but neither black). As a skybox, I inserted large blue (very large) walls to simulate the sky with no emittance and an spherical light as the "sun". My problem at this moment is that the "sun" light rays are not parallel as they should be, and the second problem is that I cannot produce shadow silluetes, just dark areas as an ambient occlusion effect. It feels as the global illumination effect is still too much for a open field scenario.

I would really appreciate any advice and many thanks in advance.

**Comment by Vethanis** [comment]
Thanks for your interest in my little project.

* The steps variable is the number of raymarching steps the shader will take per bounce. This is useful for limiting gpu time spent where the ray is parallel to the geometry's tangent and will not intersect. 
In those cases newton's method is a bit better (moving forward based on the map's derivative), but its not trivial to detect or switch back and forth. 

* To reduce noise per frame you can call trace multiple times and average those together as the value you place into the color texture. This will significantly increase gpu time taken, so you may want to ensure bounces are kept low, like 3 or 4 bounces max.

* You may want to end up using some ray tracing techniques for directional lights. Each bounce, try tracing a ray in the direction of the directional light. If your raymarch manages to get pretty far without hitting anything, go ahead and add some sunlight to that sample. This will probably take some research as I don't know it offhand.
